// Generated by vjassc phase4

globals
    integer X = 1
    real Y = 2.0
endglobals

native UnitAlive takes unit id returns boolean

function A takes nothing returns nothing
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

