// Generated by vjassc phase1

globals
endglobals


function Test takes nothing returns nothing
    call BJDebugMsg("debug")
    call BJDebugMsg("always")
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

