// Generated by vjassc phase2

globals
endglobals


function Test takes nothing returns nothing
    call BJDebugMsg("always")
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

