// Generated by vjassc phase3

globals
endglobals


function Verify takes nothing returns nothing
    local boolean b
    set b=true
    if b then
    call BJDebugMsg("vjass")
    endif
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

