// Generated by vjassc phase1

globals
endglobals


function Verify takes nothing returns nothing
    local boolean b = true
    if b then
    call BJDebugMsg("vjass")
    endif
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

