// Generated by vjassc phase4

globals
    integer ImportedValue = 1
endglobals


function MainA takes nothing returns nothing
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

