// Generated by vjassc phase1

globals
endglobals


function GetA takes nothing returns integer
    return 1
endfunction

function GetB takes nothing returns integer
    return 2
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

