// Generated by vjassc phase4

globals
    constant boolean LIBRARY_A=true
    constant boolean LIBRARY_B=true
endglobals


function AFunc takes nothing returns nothing
endfunction

function BFunc takes nothing returns nothing
    call AFunc()
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

