// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Demo=true
    integer Demo__X = 0
endglobals


function Demo___Add takes integer a, integer b returns integer
    local integer c
    set c = a + b
    return c
endfunction

function Demo___Run takes nothing returns nothing
    local integer i
    set i = 0
    loop
        exitwhen not (i < 3)
    set i = i + 1
    endloop
    if (i == 3) then
    call BJDebugMsg("ok")
    else
    call BJDebugMsg("bad")
    endif
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

