// Generated by vjassc phase5

globals
    constant boolean LIBRARY_A=true
    integer X = 1
    integer A__Y = 2
endglobals


function Foo takes nothing returns nothing
    set X = X + 1
    set A__Y = A__Y + 1
endfunction

function A___Bar takes nothing returns nothing
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

