// Generated by vjassc phase4

globals
    constant boolean LIBRARY_A=true
    integer A_X = 1
    integer A___Y = 2
endglobals


function A_Foo takes nothing returns nothing
    set A_X = A_X + 1
    set A___Y = A___Y + 1
endfunction

function A___Bar takes nothing returns nothing
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

