// Generated by vjassc phase4

globals
    integer array si__A_F
    integer si__A_I=0
    integer array si__A_V
    integer array s__A_x
endglobals


function s__A__allocate takes nothing returns integer
    local integer this
    if si__A_F[0] == 0 then
        set si__A_I=si__A_I+1
        set this=si__A_I
    else
        set this=si__A_F[0]
        set si__A_F[0]=si__A_F[this]
    endif
    set si__A_V[this]=-1
    return this
endfunction

function s__A_create takes nothing returns integer
    return s__A__allocate()
endfunction

function s__A_destroy takes integer this returns nothing
    set si__A_V[this]=0
    set si__A_F[this]=si__A_F[0]
    set si__A_F[0]=this
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
