// Generated by vjassc phase5

type rootgroup extends agent
type dzeffectgroup extends rootgroup
globals
    constant boolean LIBRARY_GroupTypes=true
    constant boolean LIBRARY_GroupConsumer=true
    dzeffectgroup lastGroup = null
    dzeffectgroup array groups
endglobals

native DzEffectGroupCreate takes nothing returns dzeffectgroup
native DzEffectGroupDestroy takes dzeffectgroup g returns boolean

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

function main takes nothing returns nothing
    local dzeffectgroup g
    set g=null
    set g = DzEffectGroupCreate()
    set groups[0] = g
    call BJDebugMsg(I2S(GetHandleId(g)))
    call DzEffectGroupDestroy(g)
    call vjassc__init_structs()
    call vjassc__init_libraries()
endfunction
