// Generated by vjassc phase5

globals
    integer array Phase14ParenArray
endglobals


function Phase14ArrayIndexParen takes nothing returns nothing
    call BJDebugMsg(I2S(Phase14ParenArray[(2)]))
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
