// Generated by vjassc phase3

globals
    constant boolean LIBRARY_Demo=true
    integer s__Demo_Queue_size=0
endglobals


function s__Demo_Queue_clear takes nothing returns nothing
    set s__Demo_Queue_size = 0
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
