// Generated by vjassc phase4

globals
    integer array si__S_F
    integer si__S_I=0
    integer array si__S_V
    trigger array vjfi__Printer_trigger
    integer vjfi__Printer_arg0
endglobals


function s__S__allocate takes nothing returns integer
    local integer this
    if si__S_F[0] == 0 then
        set si__S_I=si__S_I+1
        set this=si__S_I
    else
        set this=si__S_F[0]
        set si__S_F[0]=si__S_F[this]
    endif
    set si__S_V[this]=-1
    return this
endfunction

function s__S_create takes nothing returns integer
    return s__S__allocate()
endfunction

function s__S_destroy takes integer this returns nothing
    set si__S_V[this]=0
    set si__S_F[this]=si__S_F[0]
    set si__S_F[0]=this
endfunction

function s__S_Print takes integer x returns nothing
    call BJDebugMsg(I2S(x))
endfunction

function s__S_Test takes nothing returns nothing
    local integer p
    set p=1
    set vjfi__Printer_arg0=5
    call TriggerExecute(vjfi__Printer_trigger[p])
endfunction

function vjfi__Printer__s__S_Print__wrapper takes nothing returns nothing
    call s__S_Print(vjfi__Printer_arg0)
endfunction

function vjassc__init_function_interfaces takes nothing returns nothing
    set vjfi__Printer_trigger[1]=CreateTrigger()
    call TriggerAddAction(vjfi__Printer_trigger[1], function vjfi__Printer__s__S_Print__wrapper)
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
