// Generated by vjassc phase5

globals
endglobals


function RegisterSync takes string tag, code cb returns nothing
    if false then
    call ExecuteFunc("InitSync")
    endif
endfunction

function OnSync takes nothing returns boolean
    return true
endfunction

function InitSync takes nothing returns nothing
    call RegisterSync("OOS", function OnSync)
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

