// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Demo=true
    unit s__unitAttrObserver_argsU=null
    trigger s__unitAttrObserver_attackIntervalCB=null
endglobals


function s__unitAttrObserver_registerAttackInterval takes code func returns nothing
    call TriggerAddCondition(s__unitAttrObserver_attackIntervalCB, Condition(func))
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

