// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Phase14FunctionInterfaceUsageModes=true
    trigger array vjfi__Phase14FunctionInterfaceUsageModes___II_trigger
    unit vjfi__Phase14FunctionInterfaceUsageModes___II_arg0
    real vjfi__Phase14FunctionInterfaceUsageModes___II_arg1
    real vjfi__Phase14FunctionInterfaceUsageModes___II_arg2
    trigger array vjfi__Phase14FunctionInterfaceUsageModes___III_trigger
    player vjfi__Phase14FunctionInterfaceUsageModes___III_arg0
    real vjfi__Phase14FunctionInterfaceUsageModes___III_arg1
    real vjfi__Phase14FunctionInterfaceUsageModes___III_arg2
    integer vjfi__Phase14FunctionInterfaceUsageModes___III_result
    integer vjfi__Phase14FunctionInterfaceUsageModes___III_tmp1
    integer vjfi__Phase14FunctionInterfaceUsageModes___III_tmp2
    integer vjfi__Phase14FunctionInterfaceUsageModes___III_tmp3
    integer vjfi__Phase14FunctionInterfaceUsageModes___III_tmp4
    integer vjfi__Phase14FunctionInterfaceUsageModes___III_tmp5
    integer vjfi__Phase14FunctionInterfaceUsageModes___III_tmp6
    integer vjfi__Phase14FunctionInterfaceUsageModes___III_tmp7
    integer vjfi__Phase14FunctionInterfaceUsageModes___III_tmp8
    trigger array vjfi__Phase14FunctionInterfaceUsageModes___IV_trigger
    trigger array vjfi__Phase14FunctionInterfaceUsageModes___IIV_trigger
    integer vjfi__Phase14FunctionInterfaceUsageModes___IIV_arg0
endglobals


function ImpleII1 takes unit caster, real x, real y returns nothing
    call BJDebugMsg("II1")
endfunction

function ImpleII2 takes unit caster, real x, real y returns nothing
    call BJDebugMsg("II2")
endfunction

function ImpleIII1 takes player p, real x, real y returns integer
    return 1
endfunction

function ImpleIII2 takes player p, real x, real y returns integer
    return 2
endfunction

function ImpleIV1 takes nothing returns nothing
    call BJDebugMsg("IV1")
endfunction

function ImpleIV2 takes nothing returns nothing
    call BJDebugMsg("IV2")
endfunction

function ImpleIIV1 takes integer i returns nothing
    call BJDebugMsg(I2S(i))
endfunction

function ImpleIIV2 takes integer i returns nothing
    call BJDebugMsg(I2S(i))
endfunction

function Test takes player p returns nothing
    local integer a
    local integer b
    local integer c
    local integer d
    local integer e
    local integer f
    local integer g
    local integer h
    local integer ggg
    set a = 1
    set b = 2
    set c = 1
    set d = 2
    set e = 1
    set f = 2
    set g = 1
    set h = 2
    set vjfi__Phase14FunctionInterfaceUsageModes___II_arg0=null
    set vjfi__Phase14FunctionInterfaceUsageModes___II_arg1=0
    set vjfi__Phase14FunctionInterfaceUsageModes___II_arg2=0
    call TriggerExecute(vjfi__Phase14FunctionInterfaceUsageModes___II_trigger[a])
    set vjfi__Phase14FunctionInterfaceUsageModes___III_arg0=p
    set vjfi__Phase14FunctionInterfaceUsageModes___III_arg1=0
    set vjfi__Phase14FunctionInterfaceUsageModes___III_arg2=0
    call TriggerEvaluate(vjfi__Phase14FunctionInterfaceUsageModes___III_trigger[c])
    set ggg = vjfi__Phase14FunctionInterfaceUsageModes___III_result
    call TriggerExecute(vjfi__Phase14FunctionInterfaceUsageModes___IV_trigger[e])
    call TriggerEvaluate(vjfi__Phase14FunctionInterfaceUsageModes___IV_trigger[f])
endfunction

function vjfi__Phase14FunctionInterfaceUsageModes___II__ImpleII1_wrapper takes nothing returns nothing
    call ImpleII1(vjfi__Phase14FunctionInterfaceUsageModes___II_arg0, vjfi__Phase14FunctionInterfaceUsageModes___II_arg1, vjfi__Phase14FunctionInterfaceUsageModes___II_arg2)
endfunction

function vjfi__Phase14FunctionInterfaceUsageModes___II__ImpleII2_wrapper takes nothing returns nothing
    call ImpleII2(vjfi__Phase14FunctionInterfaceUsageModes___II_arg0, vjfi__Phase14FunctionInterfaceUsageModes___II_arg1, vjfi__Phase14FunctionInterfaceUsageModes___II_arg2)
endfunction

function vjfi__Phase14FunctionInterfaceUsageModes___III__ImpleIII1_wrapper takes nothing returns boolean
    set vjfi__Phase14FunctionInterfaceUsageModes___III_result=ImpleIII1(vjfi__Phase14FunctionInterfaceUsageModes___III_arg0, vjfi__Phase14FunctionInterfaceUsageModes___III_arg1, vjfi__Phase14FunctionInterfaceUsageModes___III_arg2)
    return true
endfunction

function vjfi__Phase14FunctionInterfaceUsageModes___III__ImpleIII2_wrapper takes nothing returns boolean
    set vjfi__Phase14FunctionInterfaceUsageModes___III_result=ImpleIII2(vjfi__Phase14FunctionInterfaceUsageModes___III_arg0, vjfi__Phase14FunctionInterfaceUsageModes___III_arg1, vjfi__Phase14FunctionInterfaceUsageModes___III_arg2)
    return true
endfunction

function vjfi__Phase14FunctionInterfaceUsageModes___IV__ImpleIV1_wrapper takes nothing returns nothing
    call ImpleIV1()
endfunction

function vjfi__Phase14FunctionInterfaceUsageModes___IV__ImpleIV2_wrapper takes nothing returns nothing
    call ImpleIV2()
endfunction

function vjassc__init_function_interfaces takes nothing returns nothing
    set vjfi__Phase14FunctionInterfaceUsageModes___II_trigger[1]=CreateTrigger()
    call TriggerAddAction(vjfi__Phase14FunctionInterfaceUsageModes___II_trigger[1], function vjfi__Phase14FunctionInterfaceUsageModes___II__ImpleII1_wrapper)
    set vjfi__Phase14FunctionInterfaceUsageModes___II_trigger[2]=CreateTrigger()
    call TriggerAddAction(vjfi__Phase14FunctionInterfaceUsageModes___II_trigger[2], function vjfi__Phase14FunctionInterfaceUsageModes___II__ImpleII2_wrapper)
    set vjfi__Phase14FunctionInterfaceUsageModes___III_trigger[1]=CreateTrigger()
    call TriggerAddCondition(vjfi__Phase14FunctionInterfaceUsageModes___III_trigger[1], Condition(function vjfi__Phase14FunctionInterfaceUsageModes___III__ImpleIII1_wrapper))
    set vjfi__Phase14FunctionInterfaceUsageModes___III_trigger[2]=CreateTrigger()
    call TriggerAddCondition(vjfi__Phase14FunctionInterfaceUsageModes___III_trigger[2], Condition(function vjfi__Phase14FunctionInterfaceUsageModes___III__ImpleIII2_wrapper))
    set vjfi__Phase14FunctionInterfaceUsageModes___IV_trigger[1]=CreateTrigger()
    call TriggerAddCondition(vjfi__Phase14FunctionInterfaceUsageModes___IV_trigger[1], Condition(function vjfi__Phase14FunctionInterfaceUsageModes___IV__ImpleIV1_wrapper))
    call TriggerAddAction(vjfi__Phase14FunctionInterfaceUsageModes___IV_trigger[1], function vjfi__Phase14FunctionInterfaceUsageModes___IV__ImpleIV1_wrapper)
    set vjfi__Phase14FunctionInterfaceUsageModes___IV_trigger[2]=CreateTrigger()
    call TriggerAddCondition(vjfi__Phase14FunctionInterfaceUsageModes___IV_trigger[2], Condition(function vjfi__Phase14FunctionInterfaceUsageModes___IV__ImpleIV2_wrapper))
    call TriggerAddAction(vjfi__Phase14FunctionInterfaceUsageModes___IV_trigger[2], function vjfi__Phase14FunctionInterfaceUsageModes___IV__ImpleIV2_wrapper)
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
