// Generated by vjassc phase5

globals
    constant boolean LIBRARY_L=true
    trigger array vjfi__Pred_trigger
    integer vjfi__Pred_arg0
    boolean vjfi__Pred_result
    boolean vjfi__Pred_tmp1
    boolean vjfi__Pred_tmp2
    boolean vjfi__Pred_tmp3
    boolean vjfi__Pred_tmp4
    boolean vjfi__Pred_tmp5
    boolean vjfi__Pred_tmp6
    boolean vjfi__Pred_tmp7
    boolean vjfi__Pred_tmp8
endglobals


function Test takes nothing returns nothing
    local integer p
    set p = 1
endfunction


function vjlambda__1 takes integer x returns boolean
    return x > 0
endfunction

function vjfi__Pred__vjlambda__1__wrapper takes nothing returns nothing
    set vjfi__Pred_result=vjlambda__1(vjfi__Pred_arg0)
endfunction

function vjassc__init_function_interfaces takes nothing returns nothing
    set vjfi__Pred_trigger[1]=CreateTrigger()
    call TriggerAddAction(vjfi__Pred_trigger[1], function vjfi__Pred__vjlambda__1__wrapper)
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
