// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Phase6Range=true
endglobals


function Sum takes integer n returns integer
    local integer i
    local integer total
    set total = 0
    set i = 1
    loop
        exitwhen not (i <= n)
    set total = total + i
    set i = i + 1
    endloop
    return total
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
