// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Phase12ArithmeticContinuation=true
endglobals


function Phase12ArithmeticContinuation_Test takes nothing returns real
    local real value
    set value = 10.0 * 2.0 / 4.0
    return value
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

