// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Phase18ZincFunction=true
endglobals


function Phase18ZincFunction___Ping takes nothing returns nothing
    call BJDebugMsg("zinc")
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

