// Generated by vjassc phase5

globals
    constant boolean LIBRARY_L=true
    integer si__Inner_F=0
    integer si__Inner_I=0
    integer array si__Inner_V
    integer array s__Inner_value
    integer si__Outer_F=0
    integer si__Outer_I=0
    integer array si__Outer_V
    integer array s__Outer_child
endglobals


function s__Inner__allocate takes nothing returns integer
    local integer this=si__Inner_F
    if (this!=0) then
        set si__Inner_F=si__Inner_V[this]
    else
        set si__Inner_I=si__Inner_I+1
        set this=si__Inner_I
    endif
    if (this>8190) then
        return 0
    endif
    set si__Inner_V[this]=-1
    return this
endfunction

function s__Inner_create takes nothing returns integer
    return s__Inner__allocate()
endfunction

function s__Inner_destroy takes integer this returns nothing
    set si__Inner_V[this]=si__Inner_F
    set si__Inner_F=this
endfunction

function s__Outer__allocate takes nothing returns integer
    local integer this=si__Outer_F
    if (this!=0) then
        set si__Outer_F=si__Outer_V[this]
    else
        set si__Outer_I=si__Outer_I+1
        set this=si__Outer_I
    endif
    if (this>8190) then
        return 0
    endif
    set si__Outer_V[this]=-1
    return this
endfunction

function s__Outer_create takes nothing returns integer
    return s__Outer__allocate()
endfunction

function s__Outer_destroy takes integer this returns nothing
    set si__Outer_V[this]=si__Outer_F
    set si__Outer_F=this
endfunction

function Test takes nothing returns integer
    local integer array nodes
    set nodes[1] = s__Outer_create()
    set s__Outer_child[nodes[1]] = s__Inner_create()
    set s__Inner_value[s__Outer_child[nodes[1]]] = 9
    return s__Inner_value[s__Outer_child[nodes[1]]]
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

