// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Phase10Continuations=true
    integer si__Builder_F=0
    integer si__Builder_I=0
    integer array si__Builder_V
    string array s__Builder_text
    trigger array vjfi__Phase10F_trigger
    integer vjfi__Phase10F_arg0
endglobals


function s__Builder__allocate takes nothing returns integer
    local integer this=si__Builder_F
    if (this!=0) then
        set si__Builder_F=si__Builder_V[this]
    else
        set si__Builder_I=si__Builder_I+1
        set this=si__Builder_I
    endif
    if (this>8190) then
        return 0
    endif
    set si__Builder_V[this]=-1
    return this
endfunction

function s__Builder_destroy takes integer this returns nothing
    set si__Builder_V[this]=si__Builder_F
    set si__Builder_F=this
endfunction

function s__Builder_create takes nothing returns integer
    local integer this
    set this = s__Builder__allocate()
    return this
endfunction

function s__Builder_append takes integer this, string left, string right returns integer
    set s__Builder_text[this] = left + right
    return this
endfunction

function s__Builder_value takes integer this returns string
    return s__Builder_text[this]
endfunction

function Use takes integer f returns nothing
    set vjfi__Phase10F_arg0=3
    call TriggerExecute(vjfi__Phase10F_trigger[f])
endfunction

function Test takes nothing returns string
    call Use(1)
    return s__Builder_value(s__Builder_append(s__Builder_create(), "a", "b")) + "-" + I2S(3)
endfunction

function Phase10Target takes integer x returns nothing
endfunction

function vjfi__Phase10F__Phase10Target__condition_wrapper takes nothing returns boolean
    call Phase10Target(vjfi__Phase10F_arg0)
    return true
endfunction

function vjfi__Phase10F__Phase10Target__action_wrapper takes nothing returns nothing
    call Phase10Target(vjfi__Phase10F_arg0)
endfunction

function vjassc__init_function_interfaces takes nothing returns nothing
    set vjfi__Phase10F_trigger[1]=CreateTrigger()
    call TriggerAddCondition(vjfi__Phase10F_trigger[1], Condition(function vjfi__Phase10F__Phase10Target__condition_wrapper))
    call TriggerAddAction(vjfi__Phase10F_trigger[1], function vjfi__Phase10F__Phase10Target__action_wrapper)
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

