// Generated by vjassc phase5

globals
    trigger array vjfi__RealFunc_trigger
    real vjfi__RealFunc_arg0
    real vjfi__RealFunc_result
    real vjfi__RealFunc_tmp1
    real vjfi__RealFunc_tmp2
    real vjfi__RealFunc_tmp3
    real vjfi__RealFunc_tmp4
    real vjfi__RealFunc_tmp5
    real vjfi__RealFunc_tmp6
    real vjfi__RealFunc_tmp7
    real vjfi__RealFunc_tmp8
endglobals


function Double takes real x returns real
    return x * 2.0
endfunction

function Test takes real x returns real
    local integer f
    set f=1
    set vjfi__RealFunc_arg0=x
    call TriggerExecute(vjfi__RealFunc_trigger[f])
    set vjfi__RealFunc_tmp1=vjfi__RealFunc_result
    set vjfi__RealFunc_arg0=vjfi__RealFunc_tmp1 + 1.0
    call TriggerExecute(vjfi__RealFunc_trigger[f])
    return vjfi__RealFunc_result
endfunction

function vjfi__RealFunc__Double__wrapper takes nothing returns nothing
    set vjfi__RealFunc_result=Double(vjfi__RealFunc_arg0)
endfunction

function vjassc__init_function_interfaces takes nothing returns nothing
    set vjfi__RealFunc_trigger[1]=CreateTrigger()
    call TriggerAddAction(vjfi__RealFunc_trigger[1], function vjfi__RealFunc__Double__wrapper)
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

