// Generated by vjassc phase5

globals
    constant boolean LIBRARY_LibA=true
    integer si__Pub_F=0
    integer si__Pub_I=0
    integer array si__Pub_V
    integer array s__Pub_x
    integer si__LibA___Priv_F=0
    integer si__LibA___Priv_I=0
    integer array si__LibA___Priv_V
    integer array s__LibA___Priv_x
endglobals


function s__Pub__allocate takes nothing returns integer
    local integer this=si__Pub_F
    if (this!=0) then
        set si__Pub_F=si__Pub_V[this]
    else
        set si__Pub_I=si__Pub_I+1
        set this=si__Pub_I
    endif
    if (this>8190) then
        return 0
    endif
    set si__Pub_V[this]=-1
    return this
endfunction

function s__Pub_create takes nothing returns integer
    return s__Pub__allocate()
endfunction

function s__Pub_destroy takes integer this returns nothing
    set si__Pub_V[this]=si__Pub_F
    set si__Pub_F=this
endfunction

function s__LibA___Priv__allocate takes nothing returns integer
    local integer this=si__LibA___Priv_F
    if (this!=0) then
        set si__LibA___Priv_F=si__LibA___Priv_V[this]
    else
        set si__LibA___Priv_I=si__LibA___Priv_I+1
        set this=si__LibA___Priv_I
    endif
    if (this>8190) then
        return 0
    endif
    set si__LibA___Priv_V[this]=-1
    return this
endfunction

function s__LibA___Priv_create takes nothing returns integer
    return s__LibA___Priv__allocate()
endfunction

function s__LibA___Priv_destroy takes integer this returns nothing
    set si__LibA___Priv_V[this]=si__LibA___Priv_F
    set si__LibA___Priv_F=this
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

