// Generated by vjassc phase3

globals
    integer array si__InitMe_F
    integer si__InitMe_I=0
    integer array si__InitMe_V
endglobals


function s__InitMe__allocate takes nothing returns integer
    local integer this
    if si__InitMe_F[0] == 0 then
        set si__InitMe_I=si__InitMe_I+1
        set this=si__InitMe_I
    else
        set this=si__InitMe_F[0]
        set si__InitMe_F[0]=si__InitMe_F[this]
    endif
    set si__InitMe_V[this]=-1
    return this
endfunction

function s__InitMe_create takes nothing returns integer
    return s__InitMe__allocate()
endfunction

function s__InitMe_destroy takes integer this returns nothing
    set si__InitMe_V[this]=0
    set si__InitMe_F[this]=si__InitMe_F[0]
    set si__InitMe_F[0]=this
endfunction

function s__InitMe_onInit takes nothing returns nothing
    call BJDebugMsg("init")
endfunction

function vjassc__init_structs takes nothing returns nothing
    call s__InitMe_onInit()
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
