// Generated by vjassc phase4

globals
    constant boolean LIBRARY_L=true
endglobals


function L_Foo takes nothing returns nothing
endfunction

function Test takes nothing returns nothing
    call ExecuteFunc("L_Foo")
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
