// Generated by vjassc phase5

globals
    integer si__Token_F=0
    integer si__Token_I=0
    integer array si__Token_V
    integer array s__Token_value
endglobals


function s__Token__allocate takes nothing returns integer
    local integer this=si__Token_F
    if (this!=0) then
        set si__Token_F=si__Token_V[this]
    else
        set si__Token_I=si__Token_I+1
        set this=si__Token_I
    endif
    if (this>8190) then
        return 0
    endif
    set si__Token_V[this]=-1
    return this
endfunction

function s__Token_create takes nothing returns integer
    return s__Token__allocate()
endfunction

function sc__Token_onDestroy takes integer this returns nothing
    set s__Token_value[this] = 0
endfunction

function s__Token_destroy takes integer this returns nothing
    call sc__Token_onDestroy(this)
    set si__Token_V[this]=si__Token_F
    set si__Token_F=this
endfunction

function KillToken takes nothing returns nothing
    local integer token
    set token=s__Token_create()
    call s__Token_destroy(token)
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
