// Generated by vjassc phase5

globals
    constant boolean LIBRARY_L=true
endglobals


function L___Test takes boolean flag returns nothing
    if (flag) then
    call BJDebugMsg("ok")
    endif
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

