// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Phase18ZincMethod=true
    integer si__Phase18ZincMethod___Box_F=0
    integer si__Phase18ZincMethod___Box_I=0
    integer array si__Phase18ZincMethod___Box_V
    integer array s__Phase18ZincMethod___Box_value
endglobals


function s__Phase18ZincMethod___Box__allocate takes nothing returns integer
    local integer this=si__Phase18ZincMethod___Box_F
    if (this!=0) then
        set si__Phase18ZincMethod___Box_F=si__Phase18ZincMethod___Box_V[this]
    else
        set si__Phase18ZincMethod___Box_I=si__Phase18ZincMethod___Box_I+1
        set this=si__Phase18ZincMethod___Box_I
    endif
    if (this>8190) then
        return 0
    endif
    set si__Phase18ZincMethod___Box_V[this]=-1
    return this
endfunction

function s__Phase18ZincMethod___Box_create takes nothing returns integer
    return s__Phase18ZincMethod___Box__allocate()
endfunction

function s__Phase18ZincMethod___Box_destroy takes integer this returns nothing
    set si__Phase18ZincMethod___Box_V[this]=si__Phase18ZincMethod___Box_F
    set si__Phase18ZincMethod___Box_F=this
endfunction

function s__Phase18ZincMethod___Box_add takes integer this, integer x returns nothing
    set s__Phase18ZincMethod___Box_value[this] = s__Phase18ZincMethod___Box_value[this] + x
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

