// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Phase10Continuations=true
    integer array si__Phase10Continuations_Builder_F
    integer si__Phase10Continuations_Builder_I=0
    integer array si__Phase10Continuations_Builder_V
    string array s__Phase10Continuations_Builder_text
    trigger array vjfi__Phase10F_trigger
    integer vjfi__Phase10F_arg0
endglobals


function s__Phase10Continuations_Builder__allocate takes nothing returns integer
    local integer this
    if si__Phase10Continuations_Builder_F[0] == 0 then
        set si__Phase10Continuations_Builder_I=si__Phase10Continuations_Builder_I+1
        set this=si__Phase10Continuations_Builder_I
    else
        set this=si__Phase10Continuations_Builder_F[0]
        set si__Phase10Continuations_Builder_F[0]=si__Phase10Continuations_Builder_F[this]
    endif
    set si__Phase10Continuations_Builder_V[this]=-1
    return this
endfunction

function s__Phase10Continuations_Builder_destroy takes integer this returns nothing
    set si__Phase10Continuations_Builder_V[this]=0
    set si__Phase10Continuations_Builder_F[this]=si__Phase10Continuations_Builder_F[0]
    set si__Phase10Continuations_Builder_F[0]=this
endfunction

function s__Phase10Continuations_Builder_create takes nothing returns integer
    local integer this
    set this = s__Phase10Continuations_Builder__allocate()
    return this
endfunction

function s__Phase10Continuations_Builder_append takes integer this, string left, string right returns integer
    set s__Phase10Continuations_Builder_text[this] = left + right
    return this
endfunction

function s__Phase10Continuations_Builder_value takes integer this returns string
    return s__Phase10Continuations_Builder_text[this]
endfunction

function Phase10Continuations_Use takes integer f returns nothing
    set vjfi__Phase10F_arg0=3
    call TriggerExecute(vjfi__Phase10F_trigger[f])
endfunction

function Phase10Continuations_Test takes nothing returns string
    call Phase10Continuations_Use(1)
    return s__Phase10Continuations_Builder_value(s__Phase10Continuations_Builder_append(s__Phase10Continuations_Builder_create(), "a", "b")) + "-" + I2S(3)
endfunction

function Phase10Target takes integer x returns nothing
endfunction

function vjfi__Phase10F__Phase10Target__wrapper takes nothing returns nothing
    call Phase10Target(vjfi__Phase10F_arg0)
endfunction

function vjassc__init_function_interfaces takes nothing returns nothing
    set vjfi__Phase10F_trigger[1]=CreateTrigger()
    call TriggerAddAction(vjfi__Phase10F_trigger[1], function vjfi__Phase10F__Phase10Target__wrapper)
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
