// Generated by vjassc phase5

globals
endglobals


function Phase13CallExternalInit takes nothing returns nothing
    call InitTrig_japi()
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

