// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Phase9PublicBlock=true
    integer HASH_TIMER = 1
    integer HASH_ABILITY = 2
endglobals


function Phase9PublicBlock___Test takes nothing returns integer
    return HASH_TIMER + HASH_ABILITY
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

