// Generated by vjassc phase5

globals
endglobals


function Phase15FastSmoke takes nothing returns nothing
    call BJDebugMsg("fast")
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
