// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Phase14FunctionObjectEvaluateCycle=true
    trigger array vjfi__vjfo__prototype1_trigger
endglobals


function TB takes nothing returns nothing
    call TriggerEvaluate(vjfi__vjfo__prototype1_trigger[1])
endfunction

function TA takes nothing returns nothing
    call TB()
endfunction

function vjfi__vjfo__prototype1__TA_wrapper takes nothing returns nothing
    call TA()
endfunction

function vjassc__init_function_interfaces takes nothing returns nothing
    set vjfi__vjfo__prototype1_trigger[1]=CreateTrigger()
    call TriggerAddCondition(vjfi__vjfo__prototype1_trigger[1], Condition(function vjfi__vjfo__prototype1__TA_wrapper))
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

