// Generated by vjassc phase5

globals
    constant boolean LIBRARY_L=true
endglobals


function L___Accept takes code first, code second returns nothing
endfunction

function vjlambda__1 takes nothing returns nothing
    call BJDebugMsg("first")
endfunction

function vjlambda__2 takes nothing returns nothing
    call BJDebugMsg("second")
endfunction

function L___Test takes nothing returns nothing
    call L___Accept(function vjlambda__1, function vjlambda__2)
endfunction


function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

