// Generated by vjassc phase5

globals
    trigger vjassc__caller__Phase13ForwardA_trigger
endglobals


function Phase13ForwardB takes nothing returns nothing
    call TriggerEvaluate(vjassc__caller__Phase13ForwardA_trigger)
endfunction

function Phase13ForwardA takes nothing returns nothing
    call Phase13ForwardB()
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

function vjassc__caller__Phase13ForwardA_wrapper takes nothing returns boolean
    call Phase13ForwardA()
    return true
endfunction

function vjassc__init_function_interfaces takes nothing returns nothing
    set vjassc__caller__Phase13ForwardA_trigger=CreateTrigger()
    call TriggerAddCondition(vjassc__caller__Phase13ForwardA_trigger, Condition(function vjassc__caller__Phase13ForwardA_wrapper))
endfunction
