// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Demo=true
    integer si__Demo___Node_F=0
    integer si__Demo___Node_I=0
    integer array si__Demo___Node_V
    integer array s__Demo___Node_value
    integer array Demo__nodes
    integer array Demo__fixed
endglobals


function s__Demo___Node__allocate takes nothing returns integer
    local integer this=si__Demo___Node_F
    if (this!=0) then
        set si__Demo___Node_F=si__Demo___Node_V[this]
    else
        set si__Demo___Node_I=si__Demo___Node_I+1
        set this=si__Demo___Node_I
    endif
    if (this>8190) then
        return 0
    endif
    set si__Demo___Node_V[this]=-1
    return this
endfunction

function s__Demo___Node_create takes nothing returns integer
    return s__Demo___Node__allocate()
endfunction

function s__Demo___Node_destroy takes integer this returns nothing
    set si__Demo___Node_V[this]=si__Demo___Node_F
    set si__Demo___Node_F=this
endfunction

function Get takes integer i, integer j returns integer
    set Demo__nodes[((i) * 3 + (j))] = s__Demo___Node_create()
    set Demo__fixed[(i)] = Demo__nodes[((i) * 3 + (j))]
    return Demo__fixed[(i)]
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

