// Generated by vjassc phase5

globals
endglobals


function ReadEnvironmentValue takes nothing returns integer
    return udg_Phase11EnvironmentValue
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
