// Generated by vjassc phase5

globals
    constant boolean LIBRARY_L=true
endglobals


function Foo takes nothing returns nothing
endfunction

function Test takes nothing returns nothing
    call ExecuteFunc("Foo")
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

