// Generated by vjassc phase5

globals
    trigger array vjfi__Action_trigger
    unit vjfi__Action_arg0
endglobals


function KillTarget takes unit u returns nothing
    call KillUnit(u)
endfunction

function Test takes unit u returns nothing
    local integer a
    set a=1
    set vjfi__Action_arg0=u
    call TriggerExecute(vjfi__Action_trigger[a])
endfunction

function vjfi__Action__KillTarget_wrapper takes nothing returns nothing
    call KillTarget(vjfi__Action_arg0)
endfunction

function vjassc__init_function_interfaces takes nothing returns nothing
    set vjfi__Action_trigger[1]=CreateTrigger()
    call TriggerAddAction(vjfi__Action_trigger[1], function vjfi__Action__KillTarget_wrapper)
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

