// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Demo=true
    string Demo__text = "/* not a comment */"
    integer Demo__raw = 'A000'
endglobals


function Use takes nothing returns nothing
    call BJDebugMsg(Demo__text + I2S(Demo__raw))
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

