// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Phase9NestedReceiver=true
    integer si__Node_F=0
    integer si__Node_I=0
    integer array si__Node_V
    integer array s__Node_value
endglobals


function s__Node__allocate takes nothing returns integer
    local integer this=si__Node_F
    if (this!=0) then
        set si__Node_F=si__Node_V[this]
    else
        set si__Node_I=si__Node_I+1
        set this=si__Node_I
    endif
    if (this>8190) then
        return 0
    endif
    set si__Node_V[this]=-1
    return this
endfunction

function s__Node_create takes nothing returns integer
    return s__Node__allocate()
endfunction

function s__Node_destroy takes integer this returns nothing
    set si__Node_V[this]=si__Node_F
    set si__Node_F=this
endfunction

function s__Node_make takes integer value returns integer
    local integer this
    set this=s__Node_create()
    set s__Node_value[this] = value
    return this
endfunction

function s__Node_get takes integer this returns integer
    return s__Node_value[this]
endfunction

function TakeValue takes integer value returns integer
    return value + 1
endfunction

function Test takes nothing returns integer
    return TakeValue(s__Node_get(s__Node_make(8)))
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

