// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Phase18JassFunction=true
endglobals


function Ping takes nothing returns nothing
    call BJDebugMsg("vjass")
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

