// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Phase11CodeParam=true
endglobals

native TakesCode takes code c returns nothing

function vjlambda__1 takes integer value returns nothing
    call BJDebugMsg(I2S(value))
endfunction

function Phase11CodeParam_Test takes nothing returns nothing
    call TakesCode(function vjlambda__1)
endfunction


function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
