// Generated by vjassc phase4

globals
    trigger array vjfi__F_trigger
    integer vjfi__F_arg0
    integer vjfi__F_result
    integer vjfi__F_tmp1
    integer vjfi__F_tmp2
    integer vjfi__F_tmp3
    integer vjfi__F_tmp4
    integer vjfi__F_tmp5
    integer vjfi__F_tmp6
    integer vjfi__F_tmp7
    integer vjfi__F_tmp8
endglobals


function Inc takes integer x returns integer
    return x + 1
endfunction

function Apply takes integer x, integer f returns integer
    set vjfi__F_arg0=x
    call TriggerExecute(vjfi__F_trigger[f])
    return vjfi__F_result
endfunction

function Test takes nothing returns integer
    return Apply(1, 1)
endfunction

function vjfi__F__Inc__wrapper takes nothing returns nothing
    set vjfi__F_result=Inc(vjfi__F_arg0)
endfunction

function vjassc__init_function_interfaces takes nothing returns nothing
    set vjfi__F_trigger[1]=CreateTrigger()
    call TriggerAddAction(vjfi__F_trigger[1], function vjfi__F__Inc__wrapper)
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
