// Generated by vjassc phase5

globals
endglobals


function InitTrig_unit takes nothing returns nothing
endfunction

function InitCustomTriggers takes nothing returns nothing
    //Function not found: call InitTrig_japi()
    call InitTrig_unit()
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

