// Generated by vjassc phase5

globals
    constant boolean LIBRARY_LifeProvider=true
    constant boolean LIBRARY_DragUser=true
    integer si__DragStruct_F=0
    integer si__DragStruct_I=0
    integer array si__DragStruct_V
    integer si__LifeStruct_F=0
    integer si__LifeStruct_I=0
    integer array si__LifeStruct_V
endglobals


function s__DragStruct__allocate takes nothing returns integer
    local integer this=si__DragStruct_F
    if (this!=0) then
        set si__DragStruct_F=si__DragStruct_V[this]
    else
        set si__DragStruct_I=si__DragStruct_I+1
        set this=si__DragStruct_I
    endif
    if (this>8190) then
        return 0
    endif
    set si__DragStruct_V[this]=-1
    return this
endfunction

function s__DragStruct_create takes nothing returns integer
    return s__DragStruct__allocate()
endfunction

function s__DragStruct_destroy takes integer this returns nothing
    set si__DragStruct_V[this]=si__DragStruct_F
    set si__DragStruct_F=this
endfunction

function s__DragStruct_onInit takes nothing returns nothing
endfunction

function s__LifeStruct__allocate takes nothing returns integer
    local integer this=si__LifeStruct_F
    if (this!=0) then
        set si__LifeStruct_F=si__LifeStruct_V[this]
    else
        set si__LifeStruct_I=si__LifeStruct_I+1
        set this=si__LifeStruct_I
    endif
    if (this>8190) then
        return 0
    endif
    set si__LifeStruct_V[this]=-1
    return this
endfunction

function s__LifeStruct_create takes nothing returns integer
    return s__LifeStruct__allocate()
endfunction

function s__LifeStruct_destroy takes integer this returns nothing
    set si__LifeStruct_V[this]=si__LifeStruct_F
    set si__LifeStruct_F=this
endfunction

function s__LifeStruct_onInit takes nothing returns nothing
endfunction

function vjassc__init_structs takes nothing returns nothing
    call s__LifeStruct_onInit()
    call s__DragStruct_onInit()
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

