// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Phase9PublicBlock=true
    integer Phase9PublicBlock_HASH_TIMER = 1
    integer Phase9PublicBlock_HASH_ABILITY = 2
endglobals


function Test takes nothing returns integer
    return Phase9PublicBlock_HASH_TIMER + Phase9PublicBlock_HASH_ABILITY
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
