// Generated by vjassc phase5

globals
    integer si__Box_F=0
    integer si__Box_I=0
    integer array si__Box_V
    unit array s__Box_u
endglobals


function s__Box__allocate takes nothing returns integer
    local integer this=si__Box_F
    if (this!=0) then
        set si__Box_F=si__Box_V[this]
    else
        set si__Box_I=si__Box_I+1
        set this=si__Box_I
    endif
    if (this>8190) then
        return 0
    endif
    set si__Box_V[this]=-1
    return this
endfunction

function s__Box_create takes nothing returns integer
    return s__Box__allocate()
endfunction

function sc__Box_onDestroy takes integer this returns nothing
    set s__Box_u[this] = null
endfunction

function s__Box_destroy takes integer this returns nothing
    call sc__Box_onDestroy(this)
    set si__Box_V[this]=si__Box_F
    set si__Box_F=this
endfunction

function Test takes nothing returns nothing
    local integer b
    set b=s__Box_create()
    call s__Box_destroy(b)
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

