// Generated by vjassc phase5

globals
    constant boolean LIBRARY_EnvCompat=true
    integer YDHT
endglobals


function ReadYDHT takes nothing returns integer
    return YDHT
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

