// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Demo=true
    integer array si__Bag_F
    integer si__Bag_I=0
    integer array si__Bag_V
    integer array s__Bag_value
    constant integer s___Bag_items_size=4
    integer array s__Bag_items
endglobals


function s__Bag__allocate takes nothing returns integer
    local integer this
    if si__Bag_F[0] == 0 then
        set si__Bag_I=si__Bag_I+1
        set this=si__Bag_I
    else
        set this=si__Bag_F[0]
        set si__Bag_F[0]=si__Bag_F[this]
    endif
    set si__Bag_V[this]=-1
    return this
endfunction

function s__Bag_create takes nothing returns integer
    return s__Bag__allocate()
endfunction

function s__Bag_destroy takes integer this returns nothing
    set si__Bag_V[this]=0
    set si__Bag_F[this]=si__Bag_F[0]
    set si__Bag_F[0]=this
endfunction

function s__Bag_reset takes integer this returns nothing
    set s__Bag_value[this] = 0
endfunction

function s__Bag_clear takes integer this, integer i returns nothing
    call s__Bag_reset(this)
    set s__Bag_items[((this) * 4 + (i))] = s__Bag_value[this]
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
