// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Phase6TypeId=true
    integer array s__Entry_value
    integer s__Entry_seen
endglobals


function s__Entry_bind takes integer index returns nothing
    set s__Entry_value[index] = 1
    set s__Entry_seen = s__Entry_value[index]
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

