// Generated by vjassc phase5

globals
    integer si__Phase15Static_F=0
    integer si__Phase15Static_I=0
    integer array si__Phase15Static_V
endglobals


function s__Phase15Static__allocate takes nothing returns integer
    local integer this=si__Phase15Static_F
    if (this!=0) then
        set si__Phase15Static_F=si__Phase15Static_V[this]
    else
        set si__Phase15Static_I=si__Phase15Static_I+1
        set this=si__Phase15Static_I
    endif
    if (this>8190) then
        return 0
    endif
    set si__Phase15Static_V[this]=-1
    return this
endfunction

function s__Phase15Static_create takes nothing returns integer
    return s__Phase15Static__allocate()
endfunction

function s__Phase15Static_destroy takes integer this returns nothing
    set si__Phase15Static_V[this]=si__Phase15Static_F
    set si__Phase15Static_F=this
endfunction

function s__Phase15Static_ping takes nothing returns integer
    return 7
endfunction

function s__Phase15Static_callPing takes integer this returns integer
    return s__Phase15Static_ping() + s__Phase15Static_ping()
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
