// Generated by vjassc phase5

globals
endglobals


function Phase13ForwardB takes nothing returns nothing
    call ExecuteFunc("Phase13ForwardA")
endfunction

function Phase13ForwardA takes nothing returns nothing
    call Phase13ForwardB()
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
