// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Phase14FunctionObjectEvaluateCycleArgs=true
    trigger array vjfi__vjfo__prototype1_trigger
    player vjfi__vjfo__prototype1_arg0
    unit vjfi__vjfo__prototype1_arg1
    integer vjfi__vjfo__prototype1_arg2
    real vjfi__vjfo__prototype1_arg3
endglobals


function TB takes player p, unit u, integer a, real b returns nothing
    set vjfi__vjfo__prototype1_arg0=p
    set vjfi__vjfo__prototype1_arg1=u
    set vjfi__vjfo__prototype1_arg2=a
    set vjfi__vjfo__prototype1_arg3=b
    call TriggerEvaluate(vjfi__vjfo__prototype1_trigger[1])
endfunction

function TF takes player p, unit u, integer a, real b returns nothing
    call TB(p, u, a, b)
endfunction

function TA takes player p, unit u, integer a, real b returns nothing
    call TB(p, u, a, b)
endfunction

function vjfi__vjfo__prototype1__TA_wrapper takes nothing returns nothing
    call TA(vjfi__vjfo__prototype1_arg0, vjfi__vjfo__prototype1_arg1, vjfi__vjfo__prototype1_arg2, vjfi__vjfo__prototype1_arg3)
endfunction

function vjassc__init_function_interfaces takes nothing returns nothing
    set vjfi__vjfo__prototype1_trigger[1]=CreateTrigger()
    call TriggerAddCondition(vjfi__vjfo__prototype1_trigger[1], Condition(function vjfi__vjfo__prototype1__TA_wrapper))
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

