// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Phase18InlineElseIfChain=true
endglobals


function Pick takes integer pj returns integer
    local integer cA
    local integer cB
    local integer cC
    set cA = 0
    set cB = 0
    set cC = 0
    if (pj == 1) then
    set cA = cA + 1
    elseif (pj == 2) then
    set cB = cB + 1
    elseif (pj == 3) then
    set cC = cC + 1
    else
    set cC = cC + 2
    endif
    return cA + cB + cC
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
