// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Phase14JassDefaultOnInit=true
    constant boolean LIBRARY_Phase14ZincDefaultOnInit=true
endglobals


function Phase14JassDefaultOnInit___onInit takes nothing returns nothing
endfunction

function Phase14ZincDefaultOnInit___onInit takes nothing returns nothing
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
    call ExecuteFunc("Phase14JassDefaultOnInit___onInit")
    call ExecuteFunc("Phase14ZincDefaultOnInit___onInit")
endfunction

