// Generated by vjassc phase5

globals
    constant boolean LIBRARY_L=true
endglobals


function L___Test takes integer x returns integer
    local integer y
    set y = 0
    if (x > 0) then
    set y = y + x
    endif
    return y
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

