// Generated by vjassc phase5

globals
    integer si__Phase18Generated_F=0
    integer si__Phase18Generated_I=0
    integer array si__Phase18Generated_V
    integer array s__Phase18Generated_value
endglobals


function s__Phase18Generated__allocate takes nothing returns integer
    local integer this=si__Phase18Generated_F
    if (this!=0) then
        set si__Phase18Generated_F=si__Phase18Generated_V[this]
    else
        set si__Phase18Generated_I=si__Phase18Generated_I+1
        set this=si__Phase18Generated_I
    endif
    if (this>8190) then
        return 0
    endif
    set si__Phase18Generated_V[this]=-1
    return this
endfunction

function s__Phase18Generated_create takes nothing returns integer
    return s__Phase18Generated__allocate()
endfunction

function s__Phase18Generated_destroy takes integer this returns nothing
    set si__Phase18Generated_V[this]=si__Phase18Generated_F
    set si__Phase18Generated_F=this
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

