// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Demo=true
    integer array Demo__grid
endglobals


function vjlambda__1 takes nothing returns nothing
    set Demo__grid[((1) * 3 + (2))] = 7
endfunction

function Register takes trigger t returns nothing
    call TriggerAddAction(t, function vjlambda__1)
endfunction


function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

