// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Phase12MethodInterfaceParam=true
    integer si__Picker_F=0
    integer si__Picker_I=0
    integer array si__Picker_V
    integer array s__Picker_cb
    trigger array vjfi__OnPick_trigger
    player vjfi__OnPick_arg0
    integer vjfi__OnPick_arg1
    integer vjfi__OnPick_arg2
endglobals


function s__Picker__allocate takes nothing returns integer
    local integer this=si__Picker_F
    if (this!=0) then
        set si__Picker_F=si__Picker_V[this]
    else
        set si__Picker_I=si__Picker_I+1
        set this=si__Picker_I
    endif
    if (this>8190) then
        return 0
    endif
    set si__Picker_V[this]=-1
    return this
endfunction

function s__Picker_destroy takes integer this returns nothing
    set si__Picker_V[this]=si__Picker_F
    set si__Picker_F=this
endfunction

function s__Picker_create takes player p, integer cb returns integer
    local integer this
    set this = s__Picker__allocate()
    set s__Picker_cb[this] = cb
    return this
endfunction

function s__Picker_fire takes integer this, player p, integer value returns nothing
    set vjfi__OnPick_arg0=p
    set vjfi__OnPick_arg1=value
    set vjfi__OnPick_arg2=this
    call TriggerExecute(vjfi__OnPick_trigger[s__Picker_cb[this]])
endfunction

function Test takes player p returns nothing
    call s__Picker_create(p, 1)
endfunction


function vjlambda__1 takes player p2, integer value, integer picker returns nothing
    call BJDebugMsg(I2S(value))
endfunction

function vjfi__OnPick__vjlambda__1_wrapper takes nothing returns nothing
    call vjlambda__1(vjfi__OnPick_arg0, vjfi__OnPick_arg1, vjfi__OnPick_arg2)
endfunction

function vjassc__init_function_interfaces takes nothing returns nothing
    set vjfi__OnPick_trigger[1]=CreateTrigger()
    call TriggerAddCondition(vjfi__OnPick_trigger[1], Condition(function vjfi__OnPick__vjlambda__1_wrapper))
    call TriggerAddAction(vjfi__OnPick_trigger[1], function vjfi__OnPick__vjlambda__1_wrapper)
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

