// Generated by vjassc phase5

globals
endglobals


function Test takes nothing returns nothing
    local integer a
    local integer b
    set a = 1
    set b = a
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

