// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Demo=true
    string Demo___text = "/* not a comment */"
    integer Demo___raw = 'A000'
endglobals


function Demo_Use takes nothing returns nothing
    call BJDebugMsg(Demo___text + I2S(Demo___raw))
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
