// Generated by vjassc phase5

globals
    integer array si__Counter_F
    integer si__Counter_I=0
    integer array si__Counter_V
    integer s__Counter_value=0
endglobals


function s__Counter__allocate takes nothing returns integer
    local integer this
    if si__Counter_F[0] == 0 then
        set si__Counter_I=si__Counter_I+1
        set this=si__Counter_I
    else
        set this=si__Counter_F[0]
        set si__Counter_F[0]=si__Counter_F[this]
    endif
    set si__Counter_V[this]=-1
    return this
endfunction

function s__Counter_create takes nothing returns integer
    return s__Counter__allocate()
endfunction

function s__Counter_destroy takes integer this returns nothing
    set si__Counter_V[this]=0
    set si__Counter_F[this]=si__Counter_F[0]
    set si__Counter_F[0]=this
endfunction

function s__Counter_add takes integer x returns nothing
    set s__Counter_value = s__Counter_value + x
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
