// Generated by vjassc phase5

globals
    constant boolean LIBRARY_ZA=true
    constant boolean LIBRARY_ZB=true
endglobals


function ZB___Test takes nothing returns nothing
    call BJDebugMsg("zinc")
    call BJDebugMsg("fallback")
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

