// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Phase12LambdaDefaultReturn=true
    trigger array vjfi__Phase12LambdaDefaultReturn___Check_trigger
    integer vjfi__Phase12LambdaDefaultReturn___Check_arg0
    boolean vjfi__Phase12LambdaDefaultReturn___Check_result
    boolean vjfi__Phase12LambdaDefaultReturn___Check_tmp1
    boolean vjfi__Phase12LambdaDefaultReturn___Check_tmp2
    boolean vjfi__Phase12LambdaDefaultReturn___Check_tmp3
    boolean vjfi__Phase12LambdaDefaultReturn___Check_tmp4
    boolean vjfi__Phase12LambdaDefaultReturn___Check_tmp5
    boolean vjfi__Phase12LambdaDefaultReturn___Check_tmp6
    boolean vjfi__Phase12LambdaDefaultReturn___Check_tmp7
    boolean vjfi__Phase12LambdaDefaultReturn___Check_tmp8
endglobals


function Test takes nothing returns nothing
    local integer check
    set check = 1
endfunction


function vjlambda__1 takes integer value returns boolean
    if (value > 0) then
    return true
    endif
    return false
endfunction

function vjassc__init_function_interfaces takes nothing returns nothing
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

