// Generated by vjassc phase5

globals
endglobals


function Test takes nothing returns integer
    local integer a
    local integer b
    local integer c
    set a=1
    set b=2
    set c = a + b
    return c
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

