// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Demo=true
    integer array si__Node_F
    integer si__Node_I=0
    integer array si__Node_V
    integer array s__Node_value
    integer array Demo___nodes
    integer array Demo___fixed
endglobals


function s__Node__allocate takes nothing returns integer
    local integer this
    if si__Node_F[0] == 0 then
        set si__Node_I=si__Node_I+1
        set this=si__Node_I
    else
        set this=si__Node_F[0]
        set si__Node_F[0]=si__Node_F[this]
    endif
    set si__Node_V[this]=-1
    return this
endfunction

function s__Node_create takes nothing returns integer
    return s__Node__allocate()
endfunction

function s__Node_destroy takes integer this returns nothing
    set si__Node_V[this]=0
    set si__Node_F[this]=si__Node_F[0]
    set si__Node_F[0]=this
endfunction

function Demo_Get takes integer i, integer j returns integer
    set Demo___nodes[((i) * 3 + (j))] = s__Node_create()
    set Demo___fixed[(i)] = Demo___nodes[((i) * 3 + (j))]
    return Demo___fixed[(i)]
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
