// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Phase14FunctionObjectEvaluateArgs=true
    unit array s__Phase14FunctionObjectEvaluateArgs___keyshop_playerU
endglobals


function Phase14FunctionObjectEvaluateArgs___RefreshProduct takes unit shopUnit, integer pos returns boolean
    return shopUnit != null and pos > 0
endfunction

function Test takes integer pid, integer idx returns nothing
    call Phase14FunctionObjectEvaluateArgs___RefreshProduct(s__Phase14FunctionObjectEvaluateArgs___keyshop_playerU[pid], idx)
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

