// Generated by vjassc phase4

globals
    constant boolean LIBRARY_Demo=true
    unit s__Demo_unitAttrObserver_argsU=null
    trigger s__Demo_unitAttrObserver_attackIntervalCB=null
endglobals


function s__Demo_unitAttrObserver_registerAttackInterval takes code func returns nothing
    call TriggerAddCondition(s__Demo_unitAttrObserver_attackIntervalCB, Condition(func))
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
