// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Demo=true
    integer si__Bag_F=0
    integer si__Bag_I=0
    integer array si__Bag_V
    constant integer s___Bag_items_size=10
    integer array s___Bag_items
    integer array s__Bag_items
endglobals


function s__Bag__allocate takes nothing returns integer
    local integer this=si__Bag_F
    if (this!=0) then
        set si__Bag_F=si__Bag_V[this]
    else
        set si__Bag_I=si__Bag_I+1
        set this=si__Bag_I
    endif
    if (this>818) then
        return 0
    endif
    set s__Bag_items[this]=(this-1)*10
    set si__Bag_V[this]=-1
    return this
endfunction

function s__Bag_create takes nothing returns integer
    return s__Bag__allocate()
endfunction

function s__Bag_destroy takes integer this returns nothing
    set si__Bag_V[this]=si__Bag_F
    set si__Bag_F=this
endfunction

function s__Bag_setItem takes integer this, integer i, integer v returns nothing
    set s___Bag_items[(s__Bag_items[this]+i)] = v
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

