// Generated by vjassc phase5

globals
    trigger array vjfi__vjfo__prototype1_trigger
    integer vjfi__vjfo__prototype1_arg0
    integer vjfi__vjfo__prototype1_result
    integer vjfi__vjfo__prototype1_tmp1
    integer vjfi__vjfo__prototype1_tmp2
    integer vjfi__vjfo__prototype1_tmp3
    integer vjfi__vjfo__prototype1_tmp4
    integer vjfi__vjfo__prototype1_tmp5
    integer vjfi__vjfo__prototype1_tmp6
    integer vjfi__vjfo__prototype1_tmp7
    integer vjfi__vjfo__prototype1_tmp8
endglobals


function Inc takes integer x returns integer
    return x + 1
endfunction

function Test takes nothing returns integer
    set vjfi__vjfo__prototype1_arg0=1
    call TriggerEvaluate(vjfi__vjfo__prototype1_trigger[1])
    return vjfi__vjfo__prototype1_result
endfunction

function vjfi__vjfo__prototype1__Inc__condition_wrapper takes nothing returns boolean
    set vjfi__vjfo__prototype1_result=Inc(vjfi__vjfo__prototype1_arg0)
    return true
endfunction

function vjassc__init_function_interfaces takes nothing returns nothing
    set vjfi__vjfo__prototype1_trigger[1]=CreateTrigger()
    call TriggerAddCondition(vjfi__vjfo__prototype1_trigger[1], Condition(function vjfi__vjfo__prototype1__Inc__condition_wrapper))
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
