// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Phase14FunctionObjectExecuteCycleArgs=true
    trigger array vjfi__vjfo__prototype1_trigger
    player vjfi__vjfo__prototype1_arg0
    unit vjfi__vjfo__prototype1_arg1
    integer vjfi__vjfo__prototype1_arg2
    real vjfi__vjfo__prototype1_arg3
endglobals


function TC takes player p, unit u, integer a, real b returns nothing
    set vjfi__vjfo__prototype1_arg0=p
    set vjfi__vjfo__prototype1_arg1=u
    set vjfi__vjfo__prototype1_arg2=a
    set vjfi__vjfo__prototype1_arg3=b
    call TriggerExecute(vjfi__vjfo__prototype1_trigger[1])
endfunction

function TD takes player p, unit u, integer a, real b returns nothing
    call TC(p, u, a, b)
endfunction

function TE takes player p, unit u, integer a, real b returns nothing
    call TD(p, u, a, b)
endfunction

function vjfi__vjfo__prototype1__TD__action_wrapper takes nothing returns nothing
    call TD(vjfi__vjfo__prototype1_arg0, vjfi__vjfo__prototype1_arg1, vjfi__vjfo__prototype1_arg2, vjfi__vjfo__prototype1_arg3)
endfunction

function vjassc__init_function_interfaces takes nothing returns nothing
    set vjfi__vjfo__prototype1_trigger[1]=CreateTrigger()
    call TriggerAddAction(vjfi__vjfo__prototype1_trigger[1], function vjfi__vjfo__prototype1__TD__action_wrapper)
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

