// Generated by vjassc phase5

globals
    constant boolean LIBRARY_L=true
endglobals


function Test takes nothing returns nothing
    local group g
    set g = CreateGroup()
    call ForGroup(g, function vjlambda__1)
endfunction


function vjlambda__2 takes nothing returns nothing
    call BJDebugMsg("nested")
endfunction

function vjlambda__1 takes nothing returns nothing
    call TimerStart(CreateTimer(), 1.0, false, function vjlambda__2)
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
