// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Phase12ArrayStructReceiver=true
    integer array s__Row_value
endglobals


function Test takes integer pos returns integer
    local integer row
    set row = (pos)
    set s__Row_value[row] = 7
    return s__Row_value[pos] + s__Row_value[row]
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

