// Generated by vjassc phase5

globals
endglobals


function MaybeValue takes boolean flag returns integer
    if flag then
    return 1
    endif
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

