// Generated by vjassc phase5

globals
    integer si__Phase15Counter_F=0
    integer si__Phase15Counter_I=0
    integer array si__Phase15Counter_V
    integer array s__Phase15Counter_value
endglobals


function s__Phase15Counter__allocate takes nothing returns integer
    local integer this=si__Phase15Counter_F
    if (this!=0) then
        set si__Phase15Counter_F=si__Phase15Counter_V[this]
    else
        set si__Phase15Counter_I=si__Phase15Counter_I+1
        set this=si__Phase15Counter_I
    endif
    if (this>8190) then
        return 0
    endif
    set si__Phase15Counter_V[this]=-1
    return this
endfunction

function s__Phase15Counter_create takes nothing returns integer
    return s__Phase15Counter__allocate()
endfunction

function s__Phase15Counter_destroy takes integer this returns nothing
    set si__Phase15Counter_V[this]=si__Phase15Counter_F
    set si__Phase15Counter_F=this
endfunction

function s__Phase15Counter_bump takes integer this returns integer
    set s__Phase15Counter_value[this] = s__Phase15Counter_value[this] + 1
    return s__Phase15Counter_value[this]
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
