// Generated by vjassc phase4

globals
    integer array si__Point_F
    integer si__Point_I=0
    integer array si__Point_V
    real array s__Point_x
    real array s__Point_y
endglobals


function s__Point__allocate takes nothing returns integer
    local integer this
    if si__Point_F[0] == 0 then
        set si__Point_I=si__Point_I+1
        set this=si__Point_I
    else
        set this=si__Point_F[0]
        set si__Point_F[0]=si__Point_F[this]
    endif
    set si__Point_V[this]=-1
    return this
endfunction

function s__Point_create takes nothing returns integer
    return s__Point__allocate()
endfunction

function s__Point_destroy takes integer this returns nothing
    set si__Point_V[this]=0
    set si__Point_F[this]=si__Point_F[0]
    set si__Point_F[0]=this
endfunction

function Test takes nothing returns nothing
    local integer p
    set p=s__Point_create()
    set s__Point_x[p] = 1.0
    set s__Point_y[p] = 2.0
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
