// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Phase12StringEqualsCall=true
endglobals


function Phase12StringEqualsCall_Test takes nothing returns nothing
    call BJDebugMsg("a=b")
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

