// Generated by vjassc phase5

globals
    constant boolean LIBRARY_L=true
endglobals


function Test takes nothing returns nothing
    call BJDebugMsg("ok")
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
