// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Phase14ChainComments=true
    integer array s__Icon_icons
endglobals


function s__Icon_create takes nothing returns integer
    return 1
endfunction

function s__Icon_setSize takes integer this, integer value returns integer
    return this
endfunction

function s__Icon_setPadding takes integer this, integer value returns integer
    return this
endfunction

function s__Icon_setPoint takes integer this, integer value returns integer
    return this
endfunction

function s__Icon_setTexture takes integer this, string value returns integer
    return this
endfunction

function s__Icon_test takes nothing returns nothing
    local integer i
    set i = 1
    set s__Icon_icons[i] = s__Icon_create()
    call s__Icon_setSize(s__Icon_icons[i], 1)
    call s__Icon_setPadding(s__Icon_icons[i], 2)
    call s__Icon_setPoint(s__Icon_icons[i], 3)
    call s__Icon_setTexture(s__Icon_icons[i], "x")
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

