// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Phase11CodeOk=true
endglobals


function vjlambda__1 takes nothing returns nothing
    call BJDebugMsg("ok")
endfunction

function Test takes trigger t returns nothing
    call TriggerAddAction(t, function vjlambda__1)
endfunction


function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

