// Generated by vjassc phase5

globals
    trigger array vjfi__BoolCheck_trigger
    integer vjfi__BoolCheck_arg0
    boolean vjfi__BoolCheck_result
    boolean vjfi__BoolCheck_tmp1
    boolean vjfi__BoolCheck_tmp2
    boolean vjfi__BoolCheck_tmp3
    boolean vjfi__BoolCheck_tmp4
    boolean vjfi__BoolCheck_tmp5
    boolean vjfi__BoolCheck_tmp6
    boolean vjfi__BoolCheck_tmp7
    boolean vjfi__BoolCheck_tmp8
endglobals


function IsPositive takes integer x returns boolean
    return x > 0
endfunction

function Test takes integer x returns boolean
    local integer check
    set check=1
    set vjfi__BoolCheck_arg0=x
    call TriggerEvaluate(vjfi__BoolCheck_trigger[check])
    return vjfi__BoolCheck_result
endfunction

function vjfi__BoolCheck__IsPositive__condition_wrapper takes nothing returns boolean
    set vjfi__BoolCheck_result=IsPositive(vjfi__BoolCheck_arg0)
    return true
endfunction

function vjassc__init_function_interfaces takes nothing returns nothing
    set vjfi__BoolCheck_trigger[1]=CreateTrigger()
    call TriggerAddCondition(vjfi__BoolCheck_trigger[1], Condition(function vjfi__BoolCheck__IsPositive__condition_wrapper))
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

