// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Phase12ElseIfTailReturn=true
endglobals


function Phase12ElseIfTailReturn_Pick takes integer value returns integer
    if (value == 1) then
    return 10
    elseif (value == 2) then
    return 20
    else
    return 30
    endif
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

