// Generated by vjassc phase4

globals
    integer array si__Tick_F
    integer si__Tick_I=0
    integer array si__Tick_V
endglobals


function s__Tick__allocate takes nothing returns integer
    local integer this
    if si__Tick_F[0] == 0 then
        set si__Tick_I=si__Tick_I+1
        set this=si__Tick_I
    else
        set this=si__Tick_F[0]
        set si__Tick_F[0]=si__Tick_F[this]
    endif
    set si__Tick_V[this]=-1
    return this
endfunction

function s__Tick_create takes nothing returns integer
    return s__Tick__allocate()
endfunction

function s__Tick_destroy takes integer this returns nothing
    set si__Tick_V[this]=0
    set si__Tick_F[this]=si__Tick_F[0]
    set si__Tick_F[0]=this
endfunction

function s__Tick_run takes nothing returns nothing
endfunction

function Test takes trigger t returns nothing
    call TriggerAddAction(t, function s__Tick_run)
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
