// Generated by vjassc phase5

globals
    trigger vjassc__caller__Phase14CycleArgA_trigger
    integer vjassc__caller__Phase14CycleArgA_arg0
    unit vjassc__caller__Phase14CycleArgA_arg1
endglobals


function Phase14CycleArgB takes integer x, unit u returns nothing
    set vjassc__caller__Phase14CycleArgA_arg0=x
    set vjassc__caller__Phase14CycleArgA_arg1=u
    call TriggerEvaluate(vjassc__caller__Phase14CycleArgA_trigger)
endfunction

function Phase14CycleArgA takes integer x, unit u returns nothing
    call Phase14CycleArgB(x, u)
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

function vjassc__caller__Phase14CycleArgA_wrapper takes nothing returns boolean
    call Phase14CycleArgA(vjassc__caller__Phase14CycleArgA_arg0, vjassc__caller__Phase14CycleArgA_arg1)
    return true
endfunction

function vjassc__init_function_interfaces takes nothing returns nothing
    set vjassc__caller__Phase14CycleArgA_trigger=CreateTrigger()
    call TriggerAddCondition(vjassc__caller__Phase14CycleArgA_trigger, Condition(function vjassc__caller__Phase14CycleArgA_wrapper))
endfunction
