// Generated by vjassc phase5

globals
    constant boolean LIBRARY_L=true
    integer array si__Node_F
    integer si__Node_I=0
    integer array si__Node_V
    integer array s__Node_value
endglobals


function s__Node__allocate takes nothing returns integer
    local integer this
    if si__Node_F[0] == 0 then
        set si__Node_I=si__Node_I+1
        set this=si__Node_I
    else
        set this=si__Node_F[0]
        set si__Node_F[0]=si__Node_F[this]
    endif
    set si__Node_V[this]=-1
    return this
endfunction

function s__Node_create takes nothing returns integer
    return s__Node__allocate()
endfunction

function s__Node_destroy takes integer this returns nothing
    set si__Node_V[this]=0
    set si__Node_F[this]=si__Node_F[0]
    set si__Node_F[0]=this
endfunction

function Test takes nothing returns integer
    local integer array nodes
    set nodes[1] = s__Node_create()
    set s__Node_value[nodes[1]] = 7
    return s__Node_value[nodes[1]]
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
