// Generated by vjassc phase4

globals
    constant boolean LIBRARY_A=true
endglobals


function Test takes nothing returns nothing
    call BJDebugMsg("A")
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

