// Generated by vjassc phase5

globals
    integer si__Phase15Shadow_F=0
    integer si__Phase15Shadow_I=0
    integer array si__Phase15Shadow_V
    integer array s__Phase15Shadow_value
endglobals


function s__Phase15Shadow__allocate takes nothing returns integer
    local integer this=si__Phase15Shadow_F
    if (this!=0) then
        set si__Phase15Shadow_F=si__Phase15Shadow_V[this]
    else
        set si__Phase15Shadow_I=si__Phase15Shadow_I+1
        set this=si__Phase15Shadow_I
    endif
    if (this>8190) then
        return 0
    endif
    set si__Phase15Shadow_V[this]=-1
    return this
endfunction

function s__Phase15Shadow_create takes nothing returns integer
    return s__Phase15Shadow__allocate()
endfunction

function s__Phase15Shadow_destroy takes integer this returns nothing
    set si__Phase15Shadow_V[this]=si__Phase15Shadow_F
    set si__Phase15Shadow_F=this
endfunction

function s__Phase15Shadow_keepLocal takes integer this, integer value returns integer
    local integer next
    set next=value + 1
    return next
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
