// Generated by vjassc phase5

globals
    integer array si__Node_F
    integer si__Node_I=0
    integer array si__Node_V
    integer array s__Node_value
    trigger array vjfi__NodeHandler_trigger
    integer vjfi__NodeHandler_arg0
    integer vjfi__NodeHandler_arg1
endglobals


function s__Node__allocate takes nothing returns integer
    local integer this
    if si__Node_F[0] == 0 then
        set si__Node_I=si__Node_I+1
        set this=si__Node_I
    else
        set this=si__Node_F[0]
        set si__Node_F[0]=si__Node_F[this]
    endif
    set si__Node_V[this]=-1
    return this
endfunction

function s__Node_create takes nothing returns integer
    return s__Node__allocate()
endfunction

function s__Node_destroy takes integer this returns nothing
    set si__Node_V[this]=0
    set si__Node_F[this]=si__Node_F[0]
    set si__Node_F[0]=this
endfunction

function s__Node_setValue takes integer this, integer value returns nothing
    set s__Node_value[this] = value
endfunction

function s__Node_Test takes nothing returns nothing
    local integer handler
    local integer node
    set handler=1
    set node=s__Node_create()
    set vjfi__NodeHandler_arg0=node
    set vjfi__NodeHandler_arg1=7
    call TriggerExecute(vjfi__NodeHandler_trigger[handler])
endfunction

function vjfi__NodeHandler__s__Node_setValue__wrapper takes nothing returns nothing
    call s__Node_setValue(vjfi__NodeHandler_arg0, vjfi__NodeHandler_arg1)
endfunction

function vjassc__init_function_interfaces takes nothing returns nothing
    set vjfi__NodeHandler_trigger[1]=CreateTrigger()
    call TriggerAddAction(vjfi__NodeHandler_trigger[1], function vjfi__NodeHandler__s__Node_setValue__wrapper)
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
