// Generated by vjassc phase3

globals
endglobals


function Test takes nothing returns nothing
    call BJDebugMsg("debug")
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

