// Generated by vjassc phase5

globals
    trigger array vjfi__IntProvider_trigger
    integer vjfi__IntProvider_result
    integer vjfi__IntProvider_tmp1
    integer vjfi__IntProvider_tmp2
    integer vjfi__IntProvider_tmp3
    integer vjfi__IntProvider_tmp4
    integer vjfi__IntProvider_tmp5
    integer vjfi__IntProvider_tmp6
    integer vjfi__IntProvider_tmp7
    integer vjfi__IntProvider_tmp8
endglobals


function FortyTwo takes nothing returns integer
    return 42
endfunction

function Test takes nothing returns integer
    local integer provider
    set provider=1
    call TriggerEvaluate(vjfi__IntProvider_trigger[provider])
    return vjfi__IntProvider_result
endfunction

function vjfi__IntProvider__FortyTwo_wrapper takes nothing returns boolean
    set vjfi__IntProvider_result=FortyTwo()
    return true
endfunction

function vjassc__init_function_interfaces takes nothing returns nothing
    set vjfi__IntProvider_trigger[1]=CreateTrigger()
    call TriggerAddCondition(vjfi__IntProvider_trigger[1], Condition(function vjfi__IntProvider__FortyTwo_wrapper))
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

