// Generated by vjassc phase5

globals
    constant boolean LIBRARY_L=true
endglobals


function L___Test takes integer x returns integer
    if (x > 0) then
    return x
    endif
    return 0
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

