// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Demo=true
    integer array si__Demo_Bag_F
    integer si__Demo_Bag_I=0
    integer array si__Demo_Bag_V
    constant integer s___Demo_Bag_items_size=10
    integer array s__Demo_Bag_items
endglobals


function s__Demo_Bag__allocate takes nothing returns integer
    local integer this
    if si__Demo_Bag_F[0] == 0 then
        set si__Demo_Bag_I=si__Demo_Bag_I+1
        set this=si__Demo_Bag_I
    else
        set this=si__Demo_Bag_F[0]
        set si__Demo_Bag_F[0]=si__Demo_Bag_F[this]
    endif
    set si__Demo_Bag_V[this]=-1
    return this
endfunction

function s__Demo_Bag_create takes nothing returns integer
    return s__Demo_Bag__allocate()
endfunction

function s__Demo_Bag_destroy takes integer this returns nothing
    set si__Demo_Bag_V[this]=0
    set si__Demo_Bag_F[this]=si__Demo_Bag_F[0]
    set si__Demo_Bag_F[0]=this
endfunction

function s__Demo_Bag_setItem takes integer this, integer i, integer v returns nothing
    set s__Demo_Bag_items[this*10+i] = v
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
