// Generated by vjassc phase5

globals
endglobals


function Inc takes integer x returns integer
    return x + 1
endfunction

function Test takes nothing returns integer
    return Inc(1)
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
