// Generated by vjassc phase5

globals
    integer si__A_F=0
    integer si__A_I=0
    integer array si__A_V
    integer array s__A_x
endglobals


function s__A__allocate takes nothing returns integer
    local integer this=si__A_F
    if (this!=0) then
        set si__A_F=si__A_V[this]
    else
        set si__A_I=si__A_I+1
        set this=si__A_I
    endif
    if (this>8190) then
        return 0
    endif
    set si__A_V[this]=-1
    return this
endfunction

function s__A_create takes nothing returns integer
    return s__A__allocate()
endfunction

function s__A_destroy takes integer this returns nothing
    set si__A_V[this]=si__A_F
    set si__A_F=this
endfunction

function s__A_foo takes integer this returns nothing
    set s__A_x[this] = s__A_x[this] + 1
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

