// Generated by vjassc phase5

globals
    constant boolean LIBRARY_LibA=true
    integer array si__LibA_Pub_F
    integer si__LibA_Pub_I=0
    integer array si__LibA_Pub_V
    integer array s__LibA_Pub_x
    integer array si__LibA___Priv_F
    integer si__LibA___Priv_I=0
    integer array si__LibA___Priv_V
    integer array s__LibA___Priv_x
endglobals


function s__LibA_Pub__allocate takes nothing returns integer
    local integer this
    if si__LibA_Pub_F[0] == 0 then
        set si__LibA_Pub_I=si__LibA_Pub_I+1
        set this=si__LibA_Pub_I
    else
        set this=si__LibA_Pub_F[0]
        set si__LibA_Pub_F[0]=si__LibA_Pub_F[this]
    endif
    set si__LibA_Pub_V[this]=-1
    return this
endfunction

function s__LibA_Pub_create takes nothing returns integer
    return s__LibA_Pub__allocate()
endfunction

function s__LibA_Pub_destroy takes integer this returns nothing
    set si__LibA_Pub_V[this]=0
    set si__LibA_Pub_F[this]=si__LibA_Pub_F[0]
    set si__LibA_Pub_F[0]=this
endfunction

function s__LibA___Priv__allocate takes nothing returns integer
    local integer this
    if si__LibA___Priv_F[0] == 0 then
        set si__LibA___Priv_I=si__LibA___Priv_I+1
        set this=si__LibA___Priv_I
    else
        set this=si__LibA___Priv_F[0]
        set si__LibA___Priv_F[0]=si__LibA___Priv_F[this]
    endif
    set si__LibA___Priv_V[this]=-1
    return this
endfunction

function s__LibA___Priv_create takes nothing returns integer
    return s__LibA___Priv__allocate()
endfunction

function s__LibA___Priv_destroy takes integer this returns nothing
    set si__LibA___Priv_V[this]=0
    set si__LibA___Priv_F[this]=si__LibA___Priv_F[0]
    set si__LibA___Priv_F[0]=this
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
