// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Phase11Init=true
endglobals


function Later takes nothing returns nothing
endfunction

function Init takes nothing returns nothing
    call ExecuteFunc("Later")
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
    call ExecuteFunc("Init")
endfunction

