// Generated by vjassc phase5

globals
endglobals


function Test takes nothing returns nothing
    local integer array a
    local integer array b
    set a[0] = 1
    set b[0] = a[0]
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
