// Generated by vjassc phase5

globals
    integer si__Counter_F=0
    integer si__Counter_I=0
    integer array si__Counter_V
    integer array s__Counter_value
    integer s__Counter_total
endglobals


function s__Counter__allocate takes nothing returns integer
    local integer this=si__Counter_F
    if (this!=0) then
        set si__Counter_F=si__Counter_V[this]
    else
        set si__Counter_I=si__Counter_I+1
        set this=si__Counter_I
    endif
    if (this>8190) then
        return 0
    endif
    set si__Counter_V[this]=-1
    return this
endfunction

function s__Counter_create takes nothing returns integer
    return s__Counter__allocate()
endfunction

function s__Counter_destroy takes integer this returns nothing
    set si__Counter_V[this]=si__Counter_F
    set si__Counter_F=this
endfunction

function s__Counter_bump takes integer this, integer delta returns integer
    local integer localValue
    set localValue=delta
    set s__Counter_value[this] = s__Counter_value[this] + localValue
    set s__Counter_total = s__Counter_total + 1
    return s__Counter_value[this]
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
