// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Demo=true
    integer si__Foo_F=0
    integer si__Foo_I=0
    integer array si__Foo_V
    integer array s__Foo_value
endglobals


function s__Foo__allocate takes nothing returns integer
    local integer this=si__Foo_F
    if (this!=0) then
        set si__Foo_F=si__Foo_V[this]
    else
        set si__Foo_I=si__Foo_I+1
        set this=si__Foo_I
    endif
    if (this>8190) then
        return 0
    endif
    set si__Foo_V[this]=-1
    return this
endfunction

function s__Foo_create takes nothing returns integer
    return s__Foo__allocate()
endfunction

function s__Foo_destroy takes integer this returns nothing
    set si__Foo_V[this]=si__Foo_F
    set si__Foo_F=this
endfunction

function s__Foo_add takes integer this, integer x returns nothing
    set s__Foo_value[this] = s__Foo_value[this] + x
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

