// Generated by vjassc phase5

globals
    integer si__Slot_F=0
    integer si__Slot_I=0
    integer array si__Slot_V
endglobals


function s__Slot__allocate takes nothing returns integer
    local integer this=si__Slot_F
    if (this!=0) then
        set si__Slot_F=si__Slot_V[this]
    else
        set si__Slot_I=si__Slot_I+1
        set this=si__Slot_I
    endif
    if (this>8190) then
        return 0
    endif
    set si__Slot_V[this]=-1
    return this
endfunction

function s__Slot_create takes nothing returns integer
    return s__Slot__allocate()
endfunction

function s__Slot_deallocate takes integer this returns nothing
    set si__Slot_V[this]=si__Slot_F
    set si__Slot_F=this
endfunction

function s__Slot_destroy takes integer this returns nothing
    call s__Slot_deallocate(this)
endfunction

function s__Slot_release takes integer this returns nothing
    call s__Slot_deallocate(this)
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
