// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Phase23ArrayStructNestedIndexReceiver=true
    integer array s__music_value
    integer array paramI
    integer array a
    integer array b
    integer array c
endglobals


function s__music_play takes integer this returns nothing
    set s__music_value[this] = s__music_value[this] + 1
endfunction

function s__music_playFor takes integer this, integer volume returns nothing
    set s__music_value[this] = volume
endfunction

function Test takes nothing returns nothing
    call s__music_play(paramI[1])
    call s__music_playFor(a[b[c[paramI[2]]]], paramI[a[b[3]]])
    set s__music_value[1006] = s__music_value[paramI[1]] + s__music_value[a[b[c[paramI[2]]]]]
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
