// Generated by vjassc phase5

globals
    trigger vjassc__caller__InitSync_trigger
endglobals


function RegisterSync takes string tag, code cb returns nothing
    if false then
    call TriggerEvaluate(vjassc__caller__InitSync_trigger)
    endif
endfunction

function OnSync takes nothing returns boolean
    return true
endfunction

function InitSync takes nothing returns nothing
    call RegisterSync("OOS", function OnSync)
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction

function vjassc__caller__InitSync_wrapper takes nothing returns boolean
    call InitSync()
    return true
endfunction

function vjassc__init_function_interfaces takes nothing returns nothing
    set vjassc__caller__InitSync_trigger=CreateTrigger()
    call TriggerAddCondition(vjassc__caller__InitSync_trigger, Condition(function vjassc__caller__InitSync_wrapper))
endfunction
