// Generated by vjassc phase5

globals
    constant boolean LIBRARY_Phase18ElseIfAfterComment=true
endglobals


function Pick takes string cmd returns integer
    local integer result
    set result = 0
    if (cmd == "atk") then
    set result = 1
    elseif (cmd == "def") then
    set result = 2
    else
    set result = 3
    endif
    return result
endfunction

function vjassc__init_structs takes nothing returns nothing
endfunction

function vjassc__init_libraries takes nothing returns nothing
endfunction
